# Generated by Django 3.2.18 on 2023-05-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(default='admin', max_length=64, verbose_name='Username'),
        ),
    ]
