# Generated by Django 3.2.18 on 2023-05-08 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_admin_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Last Name')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Address')),
                ('contact_number', models.IntegerField(max_length=11, verbose_name='Contact Number')),
                ('gender', models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], verbose_name='Gender')),
                ('create_time', models.DateField(verbose_name='Create time')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=128, verbose_name='Order ID')),
                ('title', models.CharField(max_length=32, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Product Price')),
                ('payment_status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Failed'), (4, 'Refunded'), (5, 'Cancelled')], default=1, verbose_name='Status')),
                ('delivery_status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Shipped'), (3, 'Delivered'), (4, 'Cancelled'), (5, 'Returned')], default=1, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='User')),
            ],
        ),
    ]
