# Generated by Django 3.2.18 on 2023-05-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Shipped'), (3, 'Delivered'), (4, 'Cancelled'), (5, 'Returned')], default=1, verbose_name='Delivery Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Failed'), (4, 'Refunded'), (5, 'Cancelled')], default=1, verbose_name='Payment Status'),
        ),
    ]
