# Generated by Django 3.2.18 on 2023-05-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230508_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='password',
        ),
    ]
