# Generated by Django 3.2.18 on 2023-05-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_employeeinfo_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeeinfo',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='create_time',
        ),
    ]
