# Generated by Django 3.2.18 on 2023-05-10 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230509_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.IntegerField(verbose_name='Contact Number'),
        ),
    ]
